import { prisma } from "./prisma";

/** Prisma has no native pgvector type, so embeddings are written/read as the
 * `[0.1,0.2,...]` text literal pgvector's input function expects, cast with
 * `::vector` in raw SQL. Every value is generated by us (never user input),
 * so this interpolation is safe — but we still guard against non-finite
 * numbers before it ever reaches a query string. */
function toVectorLiteral(embedding: number[]): string {
  return `[${embedding
    .map((n) => {
      if (!Number.isFinite(n)) throw new Error("Embedding contains a non-finite value");
      return n;
    })
    .join(",")}]`;
}

export interface EmbeddedChunk {
  content: string;
  embedding: number[];
}

/** Swaps out every chunk for a given source (e.g. "resume") in one transaction,
 * so re-running ingestion never leaves stale + fresh chunks mixed together. */
export async function replaceDocumentChunks(source: string, chunks: EmbeddedChunk[]) {
  await prisma.$transaction([
    prisma.$executeRaw`DELETE FROM "DocumentChunk" WHERE source = ${source}`,
    ...chunks.map((chunk, index) =>
      prisma.$executeRaw`
        INSERT INTO "DocumentChunk" (id, source, "chunkIndex", content, embedding, "createdAt")
        VALUES (
          ${crypto.randomUUID()},
          ${source},
          ${index},
          ${chunk.content},
          ${toVectorLiteral(chunk.embedding)}::vector,
          now()
        )
      `
    ),
  ]);
}

export interface RetrievedChunk {
  content: string;
  source: string;
  similarity: number;
}

/** Brute-force cosine similarity search — no ANN index needed at resume scale
 * (tens of rows), so this stays exact and skips the extra index-maintenance
 * complexity an ivfflat/hnsw index would add. */
export async function searchSimilarChunks(embedding: number[], limit = 5): Promise<RetrievedChunk[]> {
  const literal = toVectorLiteral(embedding);
  return prisma.$queryRaw<RetrievedChunk[]>`
    SELECT content, source, 1 - (embedding <=> ${literal}::vector) AS similarity
    FROM "DocumentChunk"
    ORDER BY embedding <=> ${literal}::vector
    LIMIT ${limit}
  `;
}
